tasks:      
  - name: Workspace Initialization
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      # Initialize NPM for starting containers
      cd $THEIA_WORKSPACE_ROOT/backend-flask
      pip3 install -r requirements.txt
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i      
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - 42Crunch.vscode-openapi
